# Generated by Django 2.2 on 2021-03-16 12:43

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210315_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=200, validators=[webapp.validators.MinLengthValidator(5)], verbose_name='Заголовок'),
        ),
    ]
