# Generated by Django 2.2 on 2021-03-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210315_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type_task',
            new_name='type_task_old',
        ),
    ]
