# Generated by Django 2.2 on 2021-03-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210315_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.ManyToManyField(blank=True, related_name='type', to='webapp.Task_type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task_old',
            field=models.ManyToManyField(blank=True, related_name='task_type_old', to='webapp.Task_type'),
        ),
    ]
