# Generated by Django 2.2 on 2021-03-19 12:31

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210316_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[webapp.validators.MinLengthValidator(10)], verbose_name='Описание'),
        ),
    ]
