# Generated by Django 2.2 on 2021-03-15 12:34

from django.db import migrations


def transfer_tags(apps, schema_editor):

    Task = apps.get_model('webapp.Task')

    for task in Task.objects.all():

        task.type_task.set(task.type_task_old.all())


def rollback_transfer(apps, schema_editor):

    Task = apps.get_model('webapp.Task')

    for task in Task.objects.all():

        task.type_task_old.set(task.type_task.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210315_1234'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
